# Building Image

# Base Image that sets up Node version and Linux OS
FROM node:20-alpine

# Init Work-directory
WORKDIR /app

# Include Dependencies
COPY ./package.json /app
COPY ./package-lock.json /app

# Install dependencies in the Image
RUN npm install

# Copy the codebase
COPY . /app

# CMD to run the image
CMD ["node", "server.js"]